### ISSUE TITLE
Check the style file to work with the new version of siunitx

### ISSUE THREAD

**Issue by joergklein** [mitchpaulus/siunitxext#2]
Is it possible for you to check that the script works with the new version of siunitx? I would also like to ask you to upload the source code to the CTAN?

**Comment by mitchpaulus** [comment]
@joergklein So it looks like the `number-unit-product` option has been deprecated in siunitx v3. I'll have to update that. And reading the latest documentation, there is a section about loading in custom units. The following is quoted from Section 9.16 of the siunitx documentation:

> 9.16 Creating a set of pre-defined units
There are many units which sit outside of those defined in the (current) si Brochure
which are of use to many people. Most obvious are those which have been detailed in
previous editions of the Brochure, as described in Section 6, but there are many others.
It is often convenient to have a pre-defined set of useful units available without
needing to copy the full set of definitions into each source file. At the same time,
it is important that such sources do show that they are using units not defined by
the core part of siunitx. The most straight-forward way to achieve this is to create a
separate file, for example siunitx-local-units.tex, and place it in your local TEX
tree (usually ~/texmf/tex/latex/ on Linux, ~/Library/texmf/tex/latex/ on macOS
or C:\Users\<name>\texmf\tex\latex on Windows). This can then be loaded in the
preamble using
% Load useful ’local’ units
\input{siunitx-local-units}

So what I would recommend is that you copy out the `\DeclareSIUnit` macros from the .sty file in this repo and put them in a file as the siunitx documentation recommends. 

I'll try to get around to updating the README to point others in this direction.

**Comment by mitchpaulus** [comment]
@joergklein I've made updates in response to this. I'm going to close this issue for now. Thanks for prompting the update!
